# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\JojoS\Documents\phd\JumpingRobot\nidaqmx_gui\GUI\nidaqmx_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1020, 600))
        self.centralwidget.setStyleSheet("/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: #242424;\n"
"    color: #fff;\n"
"    selection-background-color: #fff;\n"
"    selection-color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar \n"
"{\n"
"    background-color: #4a5157;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item \n"
"{\n"
"    background-color: transparent;\n"
"    border-left: 1px solid #003333;\n"
"    padding: 5px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected \n"
"{\n"
"    background-color: #003333;\n"
"    border: 1px solid #006666;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed \n"
"{\n"
"    background-color: #006666;\n"
"    border: 1px solid #006666;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #4a5157;\n"
"    border: 1px solid #4a5157;\n"
"    padding: 10px;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"    min-width: 200px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::separator\n"
"{\n"
"       background-color: #242424;\n"
"    height: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #003333;\n"
"    border: 1px solid #006666;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton \n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    padding: 3px;\n"
"    margin-left: 1px;\n"
"}\n"
"\n"
"\n"
"QToolButton:hover\n"
"{\n"
"    background-color: rgba(70,162,218,50%);\n"
"    border: 1px solid #46a2da;\n"
"    color: #000;\n"
"    \n"
"}\n"
"\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: #727272;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: #727272;\n"
"    border: 1px solid #222;\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: #4891b4;\n"
"    color: #fff;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::flat\n"
"{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #606060;\n"
"    color: #959595;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #54aad3;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #2385b4;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::checked\n"
"{\n"
"    background-color: #bd5355;\n"
"    border: 1px solid #bd5355;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    background-color: #242424;\n"
"    color : #fff;\n"
"    border: 1px solid #444444;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPlainTExtEdit-----*/\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"    color : #fff;\n"
"    border: 1px solid #1d1d1d;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolBox-----*/\n"
"QToolBox\n"
"{\n"
"    background-color: transparent;\n"
"    border: 1px solid #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolBox::tab\n"
"{\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolBox::tab:hover\n"
"{\n"
"    background-color: #006d6d;\n"
"    border: 1px solid #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QComboBox-----*/\n"
"QComboBox\n"
"{\n"
"    background-color: #4a5157;\n"
"    padding-left: 6px;\n"
"    color: #fff;\n"
"    height: 60px;\n"
"    border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    background-color: #4a5157;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: #4a5157;\n"
"    color: #fff;\n"
"    selection-background-color: #002b2b;\n"
"    selection-color: #fff;\n"
"    outline: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    background-color: #4a5157;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-radius: 4px;\n"
"    width: 15px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QDoubleSpinBox & QCalendarWidget-----*/\n"
"QDoubleSpinBox,\n"
"QCalendarWidget QSpinBox \n"
"{\n"
"    background-color: #242424;\n"
"    color : #fff;\n"
"    border: 1px solid #1d1d1d;\n"
"    border-radius: 4px;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::up-button, \n"
"QCalendarWidget QSpinBox::up-button\n"
"{\n"
"    background-color: #4a5157;\n"
"    width: 16px; \n"
"    border-top-right-radius: 4px;\n"
"    border-width: 1px;\n"
"    border-color: #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::up-button:hover, \n"
"QCalendarWidget QSpinBox::up-button:hover\n"
"{\n"
"    background-color: #585858;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::up-button:pressed, \n"
"QCalendarWidget QSpinBox::up-button:pressed\n"
"{\n"
"    background-color: #252525;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::up-arrow,\n"
"QCalendarWidget QSpinBox::up-arrow\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 7px;\n"
"    height: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::down-button, \n"
"QCalendarWidget QSpinBox::down-button\n"
"{\n"
"    background-color: #4a5157;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"    border-bottom-right-radius: 4px;\n"
"    border-color: #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::down-button:hover, \n"
"QCalendarWidget QSpinBox::down-button:hover\n"
"{\n"
"    background-color: #585858;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::down-button:pressed, \n"
"QCalendarWidget QSpinBox::down-button:pressed\n"
"{\n"
"    background-color: #252525;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::down-arrow,\n"
"QCalendarWidget QSpinBox::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 7px;\n"
"    height: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QGroupBox-----*/\n"
"QGroupBox \n"
"{\n"
"    border: 1px solid;\n"
"    border-color: #1d1d1d;\n"
"    border-radius: 4px;\n"
"    margin-top: 23px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title  \n"
"{\n"
"    background-color: #002b2b;\n"
"    color: #fff;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    padding: 5px;\n"
"    min-width: 100px;\n"
"    border: 1px solid #1d1d1d;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QHeaderView-----*/\n"
"QHeaderView::section\n"
"{\n"
"    background-color: #4a5157;\n"
"    border: none;\n"
"    color: #fff;\n"
"    padding: 4px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(227, 227, 227, 255),stop:1 rgba(187, 187, 187, 255));\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(227, 227, 227, 255),stop:1 rgba(187, 187, 187, 255));\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCalendarWidget-----*/\n"
"QCalendarWidget QToolButton\n"
"{\n"
"      background-color: transparent;\n"
"      color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QToolButton::hover\n"
"{\n"
"    background-color: #006666;\n"
"    border: 1px solid #006666;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QMenu \n"
"{\n"
"    width: 120px;\n"
"    left: 20px;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QWidget \n"
"{ \n"
"    alternate-background-color: #4a5157; \n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QAbstractItemView:enabled \n"
"{\n"
"    color: #fff;  \n"
"    background-color: #242424;  \n"
"    selection-background-color: #002b2b; \n"
"    selection-color: #fff; \n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QAbstractItemView:disabled \n"
"{ \n"
"    color: #404040; \n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeWidget-----*/\n"
"QTreeView\n"
"{\n"
"    show-decoration-selected: 0;\n"
"    alternate-background-color: transparent;\n"
"    background-color: transparent;\n"
"       border: none;\n"
"    color: #fff;\n"
"    font: 8pt;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    color:#fff;\n"
"    background-color: #002b2b;\n"
"    border-radius: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:!selected:hover\n"
"{\n"
"    background-color: #5e5e5e;\n"
"    border: none;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings \n"
"{\n"
"    image: url(://tree-closed.png);\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  \n"
"{\n"
"    image: url(://tree-open.png);\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QListView-----*/\n"
"QListView \n"
"{\n"
"    background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    border : none;\n"
"    color: #fff;\n"
"    show-decoration-selected: 1; \n"
"    outline: 0;\n"
"       border: 1px solid #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::disabled \n"
"{\n"
"    background-color: #656565;\n"
"    color: #1b1b1b;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item \n"
"{\n"
"    background-color: transparent;\n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected \n"
"{\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #002b2b;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:!active \n"
"{\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #002b2b;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:active \n"
"{\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #002b2b;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:hover {\n"
"    background-color: #5e5e5e;\n"
"    border: none;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    background-color: lightgray;\n"
"    border: 1px solid #000;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(\"./ressources/check.png\");\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #3a546e;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #46a2da; \n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QRadioButton-----*/\n"
"QRadioButton \n"
"{\n"
"    color: #fff;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked:hover \n"
"{\n"
"    background-color: #d3d3d3;\n"
"    border: 2px solid #002b2b;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked \n"
"{\n"
"    border: 2px solid #52beff;\n"
"    border-radius: 6px;\n"
"    background-color: #002b2b;  \n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:vertical \n"
"{\n"
"   border: none;\n"
"   width: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"   border: none;\n"
"   border-radius : 0px;\n"
"   background-color: #7a7a7a;\n"
"   min-height: 80px;\n"
"   width : 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical:pressed\n"
"{\n"
"   background-color: #5d5f60; \n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:vertical \n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"   background-color: #222222;\n"
"    \n"
"}\n"
"\n"
"\n"
"QScrollBar:horizontal \n"
"{\n"
"   border: none;\n"
"   height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"   border: none;\n"
"   border-radius : 0px;\n"
"   background-color: #7a7a7a;\n"
"   min-height: 80px;\n"
"   height : 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal:pressed\n"
"{\n"
"   background-color: #5d5f60; \n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:horizontal\n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:horizontal \n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"   background-color: #222222;\n"
"    \n"
"}\n"
"\n"
"\n"
"/*-----QProgressBar-----*/\n"
"QProgressBar\n"
"{\n"
"    border: 1px solid #1d1d1d;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #3b86ae;\n"
"    border-radius: 9px;\n"
"    margin: 0.5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QStatusBar-----*/\n"
"QStatusBar\n"
"{\n"
"    background-color: #4a5157;\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QSizeGrip-----*/\n"
"QSizeGrip \n"
"{\n"
"    background-color: image(\"./ressources/sizegrip.png\"); /*To replace*/\n"
"    border: none;\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_leftColumn = QtWidgets.QVBoxLayout()
        self.verticalLayout_leftColumn.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_leftColumn.setObjectName("verticalLayout_leftColumn")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 10, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_OpenCalib = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OpenCalib.setObjectName("pushButton_OpenCalib")
        self.horizontalLayout_2.addWidget(self.pushButton_OpenCalib)
        self.lineEdit_OpenCalib = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OpenCalib.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_OpenCalib.setObjectName("lineEdit_OpenCalib")
        self.horizontalLayout_2.addWidget(self.lineEdit_OpenCalib)
        self.verticalLayout_leftColumn.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_leftColumn.addItem(spacerItem)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_ChannelParam = QtWidgets.QLabel(self.centralwidget)
        self.label_ChannelParam.setObjectName("label_ChannelParam")
        self.verticalLayout_5.addWidget(self.label_ChannelParam)
        self.comboBox_DAQCard = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_DAQCard.setObjectName("comboBox_DAQCard")
        self.verticalLayout_5.addWidget(self.comboBox_DAQCard)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_ChannelFirst = QtWidgets.QLabel(self.centralwidget)
        self.label_ChannelFirst.setObjectName("label_ChannelFirst")
        self.horizontalLayout_3.addWidget(self.label_ChannelFirst)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lineEdit_ChannelFirst = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ChannelFirst.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_ChannelFirst.setObjectName("lineEdit_ChannelFirst")
        self.horizontalLayout_3.addWidget(self.lineEdit_ChannelFirst)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem2)
        self.label_TimingParam = QtWidgets.QLabel(self.centralwidget)
        self.label_TimingParam.setObjectName("label_TimingParam")
        self.verticalLayout_5.addWidget(self.label_TimingParam)
        self.label_SetTimingParams = QtWidgets.QLabel(self.centralwidget)
        self.label_SetTimingParams.setWordWrap(True)
        self.label_SetTimingParams.setObjectName("label_SetTimingParams")
        self.verticalLayout_5.addWidget(self.label_SetTimingParams)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_SampleFreq = QtWidgets.QLabel(self.centralwidget)
        self.label_SampleFreq.setObjectName("label_SampleFreq")
        self.horizontalLayout_6.addWidget(self.label_SampleFreq)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.lineEdit_SampleFreq = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_SampleFreq.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_SampleFreq.setObjectName("lineEdit_SampleFreq")
        self.horizontalLayout_6.addWidget(self.lineEdit_SampleFreq)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_BufferSize = QtWidgets.QLabel(self.centralwidget)
        self.label_BufferSize.setObjectName("label_BufferSize")
        self.horizontalLayout_7.addWidget(self.label_BufferSize)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.lineEdit_BufferSize = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_BufferSize.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_BufferSize.setObjectName("lineEdit_BufferSize")
        self.horizontalLayout_7.addWidget(self.lineEdit_BufferSize)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_PostTriggerSamples = QtWidgets.QLabel(self.centralwidget)
        self.label_PostTriggerSamples.setObjectName("label_PostTriggerSamples")
        self.horizontalLayout_10.addWidget(self.label_PostTriggerSamples)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.lineEdit_PostTriggerSamples = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_PostTriggerSamples.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_PostTriggerSamples.setObjectName("lineEdit_PostTriggerSamples")
        self.horizontalLayout_10.addWidget(self.lineEdit_PostTriggerSamples)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.label_SetUnitParams = QtWidgets.QLabel(self.centralwidget)
        self.label_SetUnitParams.setWordWrap(True)
        self.label_SetUnitParams.setObjectName("label_SetUnitParams")
        self.verticalLayout_5.addWidget(self.label_SetUnitParams)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_ForceUnits = QtWidgets.QLabel(self.centralwidget)
        self.label_ForceUnits.setObjectName("label_ForceUnits")
        self.horizontalLayout_8.addWidget(self.label_ForceUnits)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.comboBox_ForceUnits = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ForceUnits.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_ForceUnits.setObjectName("comboBox_ForceUnits")
        self.horizontalLayout_8.addWidget(self.comboBox_ForceUnits)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_TorqueUnits = QtWidgets.QLabel(self.centralwidget)
        self.label_TorqueUnits.setObjectName("label_TorqueUnits")
        self.horizontalLayout_9.addWidget(self.label_TorqueUnits)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.comboBox_TorqueUnits = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_TorqueUnits.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_TorqueUnits.setCurrentText("")
        self.comboBox_TorqueUnits.setObjectName("comboBox_TorqueUnits")
        self.horizontalLayout_9.addWidget(self.comboBox_TorqueUnits)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        spacerItem8 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem8)
        self.pushButton_Bias = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Bias.setCheckable(True)
        self.pushButton_Bias.setObjectName("pushButton_Bias")
        self.verticalLayout_5.addWidget(self.pushButton_Bias)
        self.pushButton_Unbias = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Unbias.setCheckable(True)
        self.pushButton_Unbias.setObjectName("pushButton_Unbias")
        self.verticalLayout_5.addWidget(self.pushButton_Unbias)
        self.verticalLayout_leftColumn.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_info = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_info.setLineWidth(3)
        self.listWidget_info.setObjectName("listWidget_info")
        self.verticalLayout_3.addWidget(self.listWidget_info)
        self.verticalLayout_leftColumn.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_leftColumn)
        self.verticalLayout_middleColumn = QtWidgets.QVBoxLayout()
        self.verticalLayout_middleColumn.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_middleColumn.setObjectName("verticalLayout_middleColumn")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_Record = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Record.setCheckable(True)
        self.pushButton_Record.setObjectName("pushButton_Record")
        self.horizontalLayout_4.addWidget(self.pushButton_Record)
        self.pushButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stop.setMinimumSize(QtCore.QSize(90, 20))
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.horizontalLayout_4.addWidget(self.pushButton_Stop)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout_middleColumn.addLayout(self.horizontalLayout_4)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_middleColumn.addItem(spacerItem10)
        self.frame_livePreview = QtWidgets.QFrame(self.centralwidget)
        self.frame_livePreview.setMinimumSize(QtCore.QSize(600, 480))
        self.frame_livePreview.setStyleSheet("QFrame {border: 3px solid #000000;}")
        self.frame_livePreview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_livePreview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_livePreview.setObjectName("frame_livePreview")
        self.verticalLayout_middleColumn.addWidget(self.frame_livePreview)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_middleColumn.addItem(spacerItem11)
        self.horizontalLayout.addLayout(self.verticalLayout_middleColumn)
        self.verticalLayout_rightColumn = QtWidgets.QVBoxLayout()
        self.verticalLayout_rightColumn.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_rightColumn.setObjectName("verticalLayout_rightColumn")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_rightColumn.addItem(spacerItem12)
        self.checkBox_Fx = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Fx.setObjectName("checkBox_Fx")
        self.verticalLayout_rightColumn.addWidget(self.checkBox_Fx)
        self.checkBox_Fy = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Fy.setObjectName("checkBox_Fy")
        self.verticalLayout_rightColumn.addWidget(self.checkBox_Fy)
        self.checkBox_Fz = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Fz.setObjectName("checkBox_Fz")
        self.verticalLayout_rightColumn.addWidget(self.checkBox_Fz)
        self.checkBox_Tx = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Tx.setObjectName("checkBox_Tx")
        self.verticalLayout_rightColumn.addWidget(self.checkBox_Tx)
        self.checkBox_Ty = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Ty.setObjectName("checkBox_Ty")
        self.verticalLayout_rightColumn.addWidget(self.checkBox_Ty)
        self.checkBox_Tz = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Tz.setObjectName("checkBox_Tz")
        self.verticalLayout_rightColumn.addWidget(self.checkBox_Tz)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_rightColumn.addItem(spacerItem13)
        self.horizontalLayout.addLayout(self.verticalLayout_rightColumn)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.pushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout_5.addWidget(self.pushButton_Save)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_ForceUnits.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_OpenCalib.setText(_translate("MainWindow", "Open"))
        self.lineEdit_OpenCalib.setText(_translate("MainWindow", "calibration file"))
        self.label_ChannelParam.setText(_translate("MainWindow", "CHANNEL PARAMETERS"))
        self.label_ChannelFirst.setText(_translate("MainWindow", "First channel:"))
        self.lineEdit_ChannelFirst.setText(_translate("MainWindow", "0"))
        self.label_TimingParam.setText(_translate("MainWindow", "TIMING PARAMETERS"))
        self.label_SetTimingParams.setText(_translate("MainWindow", "Set the sample frequncy and the buffer size: E.g. if Frequency = 1000 and Buffer size = 1000, the resulting recording will be 1s"))
        self.label_SampleFreq.setText(_translate("MainWindow", "Sample Frequency (Hz)"))
        self.lineEdit_SampleFreq.setText(_translate("MainWindow", "1000"))
        self.label_BufferSize.setText(_translate("MainWindow", "Buffer Size (Samples)"))
        self.lineEdit_BufferSize.setText(_translate("MainWindow", "3000"))
        self.label_PostTriggerSamples.setText(_translate("MainWindow", "Post-Trigger Samples"))
        self.lineEdit_PostTriggerSamples.setText(_translate("MainWindow", "0"))
        self.label_SetUnitParams.setText(_translate("MainWindow", "Define the units for forces and torques. If 'None' the units from the calibration file will be used."
                                                                  "If you want to change units after having loaded the calibration file, the file has to be reloaded to perform calibration again."))
        self.label_ForceUnits.setText(_translate("MainWindow", "Force Units"))
        self.label_TorqueUnits.setText(_translate("MainWindow", "Torque Units"))
        self.pushButton_Bias.setText(_translate("MainWindow", "Bias"))
        self.pushButton_Unbias.setText(_translate("MainWindow", "Unbias"))
        self.pushButton_Record.setText(_translate("MainWindow", "RECORD"))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop"))
        self.checkBox_Fx.setText(_translate("MainWindow", "Fx"))
        self.checkBox_Fy.setText(_translate("MainWindow", "Fy"))
        self.checkBox_Fz.setText(_translate("MainWindow", "Fz"))
        self.checkBox_Tx.setText(_translate("MainWindow", "Tx"))
        self.checkBox_Ty.setText(_translate("MainWindow", "Ty"))
        self.checkBox_Tz.setText(_translate("MainWindow", "Tz"))
        self.pushButton_Save.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
